

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: CLOUD-CONFIG-SERVER
  profiles:
    active: git
  cloud:
    config:
      override-system-properties: false
      server:
        git:
          uri: https://github.com/rathore99/microservice-config-server
          default-label: main
    bus:
      enabled: true
    kafka:
      bootstrap-servers: ${KAFKA_ADDR:http://localhost:9092}